[[dependency]]
org = "samjs"
name = "checkpanic_analyzer"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha5"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"


